export const ADMIN_ROUTE = '/admin' 
export const LOGIN_ROUTE = '/login'
export const MAP_ROUTE = '/map'
export const PRODUCT_ROUTE = '/product'
export const REGISTRATION_ROUTE = '/registration'
export const MAIN_ROUTE = '/'
export const COMPARE = '/compare'